cluster:
  databaseID: aaaabbbbccccddddeeee # Specify your databaseID
  databaseQuery: >
    {
    }
  collectDumpID: aaaabbbbccccddddeeee # Write to BlockID
  collectDumpBlockToggle: >
    {
      "object": "block",
      "type": "toggle",
      "toggle": {
        "text": [
          {
            "type": "text",
            "text": {
              "content": "{{.Title}}"
            }
          }
        ],
        "children": []
      }
    }
  collectDumpBlock: >
    {
        "object": "block",
        "type": "paragraph",
        "paragraph": {
            "text": [
                {
                    "type": "mention",
                    "mention": {
                        "type": "page",
                        "page": {
                            "id": "{{.PageID}}"
                        }
                    }
                }
            ]
        }
    }